Repository ZZANTech/ZZANTech-Fe, pull requests merged in 2024-08, with the labels that each got.

#150 Feature/gift
  src/apis/auth/mypage/mypageInfo.ts
  src/apis/exchange.ts
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/boards/knowhow/_constants/index.ts
  src/app/(main)/exchange/_components/ClaimContainer.tsx
  src/app/(main)/exchange/_components/ClaimItem.tsx
  src/app/(main)/exchange/_components/ClaimList.tsx
  src/app/(main)/exchange/_components/ExchangeContainer.tsx
  src/app/(main)/exchange/_components/GiftContainer.tsx
  src/app/(main)/exchange/_components/GiftItem.tsx
  src/app/(main)/exchange/_components/GiftList.tsx
  src/app/(main)/exchange/page.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/mypage/like/_components/LikedKnowhowContainer.tsx
  src/app/(main)/mypage/like/loading.tsx
  src/app/(main)/mypage/like/page.tsx
  src/app/(main)/mypage/posts/_components/FilterOption.tsx
  src/app/(main)/mypage/posts/_components/MyKnowhowContainer.tsx
  src/app/(main)/mypage/posts/_components/MyPostsContainer.tsx
  src/app/(main)/mypage/posts/_components/MyVotesContainer.tsx
  src/app/api/exchange/[userId]/route.ts
  src/app/api/exchange/claim/[giftId]/route.ts
  src/app/api/exchange/gift/route.ts
  src/app/layout.tsx
  src/stores/queries/useClaimsQuery.ts
  src/stores/queries/useExchangeMutation.ts
  src/stores/queries/useGiftsQuery.ts
  src/types/exchange.type.ts
  src/types/supabase.ts
Labels: feature

#151 feat: 닉네임 변경모달 추가
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/NicknameModal.tsx
  src/provider/contexts/ModalContext.tsx
  src/types/modal.type.ts
Labels: feature

#152 feat/vote-detail-page-ui 짠 소비 상세 페이지 UI
  public/icons/vote/direction=left, state=Default.png
  public/icons/vote/direction=left, state=hover.png
  public/icons/vote/direction=left, state=nonactive.png
  public/icons/vote/direction=right, state=Default.png
  public/icons/vote/direction=right, state=hover.png
  public/icons/vote/direction=right, state=nonactive.png
  public/icons/vote/downvote.png
  public/icons/vote/upvote.png
  src/app/(main)/boards/votes/[voteId]/_components/ActionNav.tsx
  src/app/(main)/boards/votes/[voteId]/_components/NavButton.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteButtons.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteContent.tsx
  src/app/(main)/boards/votes/[voteId]/page.tsx
Labels: feature

#153 Feature/mypage : 마이페이지 첫 화면, 비밀번호 변경 디자인 적용, 닉네임 변경 모달창 (Provider 변경🚨)
  public/icons/mypage/coin.png
  public/icons/mypage/heart.png
  public/icons/mypage/lv1.png
  public/icons/mypage/lv2.png
  public/icons/mypage/lv3.png
  public/icons/mypage/lv4.png
  public/icons/mypage/lv5.png
  public/icons/mypage/pencil_white.png
  public/icons/mypage/right_arrow.png
  src/apis/auth.ts
  src/app/(auth)/_utils/authValidation.ts
  src/app/(main)/mypage/_components/InfoContainer.tsx
  src/app/(main)/mypage/_components/LevelContainer.tsx
  src/app/(main)/mypage/_components/MyPosts/MyPostsContainer.tsx
  src/app/(main)/mypage/_components/MypageContainer.tsx
  src/app/(main)/mypage/_components/OtherPosts/OtherPostsContainer.tsx
  src/app/(main)/mypage/_components/PointContainer.tsx
  src/app/(main)/mypage/_utils/checkLevel.ts
  src/app/(main)/mypage/edit/_components/TestPassword.tsx
  src/app/(main)/mypage/edit/_components/TestUpdatePassword.tsx
  src/app/(main)/mypage/edit/_components/UserEditContainer.tsx
  src/app/(main)/mypage/edit/_components/UserEditNickname.tsx
  src/app/(main)/mypage/edit/_components/UserEditPassword.tsx
  src/app/(main)/mypage/edit/_components/checkValidity.tsx
  src/app/(main)/mypage/edit/page.tsx
  src/app/api/auth/mypage/nickname/route.ts
  src/components/Modal/NicknameModal.tsx
  src/provider/Providers.tsx
Labels: feature

#155 fix: 기프티콘 페이지 버그 수정
  src/apis/exchange.ts
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/boards/knowhow/_constants/index.ts
  src/app/(main)/exchange/_components/ClaimContainer.tsx
  src/app/(main)/exchange/_components/ClaimItem.tsx
  src/app/(main)/exchange/_components/GiftItem.tsx
  src/app/(main)/exchange/page.tsx
  src/app/api/exchange/[userId]/route.ts
  src/app/api/exchange/claim/[giftId]/route.ts
  src/stores/queries/useClaimsQuery.ts
  src/stores/queries/useExchangeMutation.ts
Labels: bug

#156 fix: 내글 목록에서 글이 없으면 에러가 나는문제 / design: pagination 및 serach option UI
  public/icons/filter/arrow_left.svg
  public/icons/filter/arrow_right.svg
  public/icons/filter/double_arrow_left.svg
  public/icons/filter/double_arrow_right.svg
  public/icons/filter/search.svg
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/boards/knowhow/_components/Pagination.tsx
  src/app/(main)/boards/knowhow/_components/SearchOptions.tsx
  src/app/(main)/mypage/posts/_components/MyKnowhowContainer.tsx
  src/app/(main)/mypage/posts/_components/MyVotesContainer.tsx
  src/app/api/votes/posts/my/[userId]/route.ts
Labels: bug, feature

#158 feat: 모달 우측상단 X버튼 추가, 버튼의 텍스트를 변경할수 있도록 수정, 모달 UI작업
  public/icons/x_btn.svg
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/components/Modal/AlertModal.tsx
  src/components/Modal/ConfirmModal.tsx
  src/components/Modal/DefaultModalTemplate.tsx
  src/components/Modal/Modal.tsx
  src/hooks/useAlertModal.ts
  src/provider/contexts/ModalContext.tsx
  src/types/modal.type.ts
Labels: feature

#162 feat: 게시판 비밀번호 변경 및 상품 교환페이지 모달처리
  src/apis/exchange.ts
  src/app/(auth)/_utils/authValidation.ts
  src/app/(main)/boards/_components/Comments/CommentForm.tsx
  src/app/(main)/boards/_components/Comments/CommentItem.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/_components/ActionNav.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowEditor.tsx
  src/app/(main)/boards/votes/[voteId]/_components/ActionNav.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteButtons.tsx
  src/app/(main)/boards/votes/_components/VoteWriteForm.tsx
  src/app/(main)/exchange/_components/ExchangeContainer.tsx
  src/app/(main)/exchange/_components/GiftItem.tsx
  src/app/(main)/mypage/posts/_components/FilterOption.tsx
  src/app/api/auth/mypage/password/route.ts
  src/hooks/useConfirmModal.ts
  src/stores/queries/useChangePasswordMutation.ts
  src/stores/queries/useExchangeMutation.ts
  src/utils/splitMessage.ts
Labels: feature

#165 feature/user-points-detail-page 포인트 내역 페이지 페이지네이션, UI
  public/icons/mypage/coin.png
  public/icons/mypage/shopping.png
  src/apis/point.ts
  src/app/(main)/mypage/_components/Points/MyCurrentPoints.tsx
  src/app/(main)/mypage/_components/Points/MyPointsHistoryTable.tsx
  src/app/(main)/mypage/point/page.tsx
  src/app/api/points/[userId]/route.ts
  src/stores/queries/usePointsQuery.ts
  src/types/point.type.ts
Labels: feature

#166 fix: 짠 소비평가의 투표가 비정상적이게 작동하던 문제
  src/app/(main)/boards/votes/[voteId]/_components/VoteButtons.tsx
  src/app/api/votes/[voteId]/like/route.ts
  src/stores/queries/useVoteLikeMutation.ts
Labels: bug, feature

#176 feat/vote-ui 짠 소비 목록 페이지 UI
  src/app/(main)/boards/_components/BoardDescription.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowFilter.tsx
  src/app/(main)/boards/knowhow/_components/SortOptions.tsx
  src/app/(main)/boards/knowhow/page.tsx
  src/app/(main)/boards/votes/_components/SortButtons.tsx
  src/app/(main)/boards/votes/_components/VoteItem.tsx
  src/app/(main)/boards/votes/_components/VotesContainer.tsx
  src/app/(main)/boards/votes/_components/VotesList.tsx
  src/app/(main)/boards/votes/page.tsx
Labels: feature

#180 feature/vote-ui 짠 소비 작성 페이지 UI 마무리 작업
  src/app/(main)/boards/votes/_components/VoteWriteForm.tsx
Labels: feature

#184 design: knowhow페이지 및 내가 쓴 글, 좋아요 누른 글 UI / feat: 좋아요 누른 글 정렬기준 변경
  src/app/(main)/boards/knowhow/[knowhowId]/_components/ActionNav.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/_components/KnowhowLikes.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/_components/PostActions.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/_components/PostContent.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/page.tsx
  src/app/(main)/boards/knowhow/_components/ErrorMessage.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowEditor.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowFilter.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowList.tsx
  src/app/(main)/boards/knowhow/_components/SkeletonKnowhowItem.tsx
  src/app/(main)/boards/knowhow/_components/SkeletonKnowhowList.tsx
  src/app/(main)/boards/knowhow/_components/knowhowItem/KnowhowItem.tsx
  src/app/(main)/boards/votes/_components/SkeletonVoteItem.tsx
  src/app/(main)/boards/votes/_components/SkeletonVoteList.tsx
  src/app/(main)/boards/votes/_components/VotesContainer.tsx
  src/app/(main)/mypage/like/_components/LikedKnowhowContainer.tsx
  src/app/(main)/mypage/posts/_components/MyKnowhowContainer.tsx
  src/app/(main)/mypage/posts/_components/MyVotesContainer.tsx
  src/app/api/knowhow/my/like/[userId]/route.ts
  src/app/globals.css
  src/stores/queries/useKnowhowLikeMutation.ts
  src/types/supabase.ts
Labels: feature

#185 feat: 교환신청 내역이 없을경우 메시지 표기
  src/app/(main)/exchange/_components/ClaimContainer.tsx
  src/app/(main)/mypage/like/_components/LikedKnowhowContainer.tsx
  src/app/(main)/mypage/posts/_components/MyKnowhowContainer.tsx
  src/app/(main)/mypage/posts/_components/MyVotesContainer.tsx
  src/app/(main)/mypage/posts/_components/NoPostsMessage.tsx
Labels: feature

#188 feat/vote-ui 짠 소비 상세 페이지 및 댓글 컴포넌트 UI
  public/icons/mypage/pen_white.png
  src/app/(main)/boards/_components/Comments/CommentEditForm.tsx
  src/app/(main)/boards/_components/Comments/CommentForm.tsx
  src/app/(main)/boards/_components/Comments/CommentItem.tsx
  src/app/(main)/boards/_components/Comments/CommentsContainer.tsx
  src/app/(main)/boards/_components/Comments/CommentsList.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteButtons.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteContent.tsx
Labels: feature

#157 Feature/mypage: 마이페이지 닉네임 변경 update API 해결
  src/apis/auth.ts
  src/app/(main)/boards/knowhow/_components/SearchOptions.tsx
  src/app/(main)/mypage/_components/LevelContainer.tsx
  src/app/(main)/mypage/_components/PointContainer.tsx
  src/app/(main)/mypage/_utils/checkLevel.ts
  src/app/api/auth/mypage/nickname/route.ts
  src/app/api/knowhow/route.ts
  src/components/Modal/NicknameModal.tsx
Labels: feature

#191 feat: 마이페이지 등급제 설명 페이지
  public/icons/mypage/green_twinkle.png
  src/app/(auth)/signUp/_components/PasswordForm.tsx
  src/app/(main)/@GradeModal/(.)mypage/grade/page.tsx
  src/app/(main)/@GradeModal/default.tsx
  src/app/(main)/@QuizModal/(.)quiz/page.tsx
  src/app/(main)/@QuizModal/default.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/mypage/_components/Grade/GradeInfo.tsx
  src/app/(main)/mypage/_components/Grade/GradeInfoContainer.tsx
  src/app/(main)/mypage/_components/Grade/GradeModal.tsx
  src/app/(main)/mypage/_components/LevelContainer.tsx
  src/app/(main)/mypage/grade/page.tsx
Labels: feature

#194 Feature/mypage
  src/apis/auth.ts
  src/app/(auth)/login/_components/LoginContainer.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/loading.tsx
  src/app/(main)/boards/votes/[voteId]/loading.tsx
  src/app/(main)/mypage/_components/InfoContainer.tsx
  src/app/(main)/mypage/_components/LevelContainer.tsx
  src/app/(main)/mypage/_components/MyPosts/MyPostsContainer.tsx
  src/app/(main)/mypage/_components/MypageContainer.tsx
  src/app/(main)/mypage/_components/OtherPosts/OtherPostsContainer.tsx
  src/app/(main)/mypage/_components/PointContainer.tsx
  src/app/(main)/mypage/like/page.tsx
  src/app/(main)/mypage/loading.tsx
  src/components/Modal/NicknameModal.tsx
  src/utils/authValidity.ts
Labels: feature

#197 fix: 퀴즈 제출 중복 방지를 위해 버튼 비활성화 추가
  src/app/(main)/quiz/_components/QuizQuestion.tsx
Labels: bug

#206 Feature/mypage: 로그인 오류메시지 실시간 업데이트 기능 삭제, 고정 오류메시지 설정, Auth 관련 컴포넌트 불필요한 파일 및 폴더, 코드 삭제
  src/apis/auth.ts
  src/apis/auth/mypage/mypageInfo.ts
  src/apis/signup.ts
  src/app/(auth)/_utils/authValidation.ts
  src/app/(auth)/login/_components/LoginContainer.tsx
  src/app/(auth)/signUp/_components/EmailForm.tsx
  src/app/(auth)/signUp/_components/NicknameForm.tsx
  src/app/(auth)/signUp/_components/PasswordForm.tsx
  src/app/(auth)/signUp/_components/RecheckPasswordForm.tsx
  src/app/(auth)/signUp/_components/SignUpContainer.tsx
  src/app/(main)/mypage/_components/InfoContainer.tsx
  src/app/(main)/mypage/_components/MyPostsContainer.tsx
  src/app/(main)/mypage/_components/MypageContainer.tsx
  src/app/(main)/mypage/_components/OtherPosts/OtherPostsContainer.tsx
  src/app/(main)/mypage/_components/OtherPostsContainer.tsx
  src/app/(main)/mypage/_components/PointContainer.tsx
  src/app/(main)/mypage/edit/_components/UserEditPassword.tsx
  src/app/api/auth/login/route.ts
  src/app/globals.css
  src/components/Modal/NicknameModal.tsx
  src/utils/authValidity.ts
Labels: feature

#210 chore: 비밀번호 오류 메시지 변경
  src/app/(auth)/_utils/authValidation.ts
Labels: feature

#212 feat: 간단한 메타데이터 설정 / design: 짠 노하우 페이지 search 바 아웃라인 제거
  src/app/(main)/boards/knowhow/[knowhowId]/page.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/boards/knowhow/_components/SearchOptions.tsx
  src/app/(main)/boards/knowhow/page.tsx
  src/app/(main)/boards/votes/[voteId]/page.tsx
  src/app/(main)/boards/votes/page.tsx
  src/app/(main)/chat/page.tsx
  src/app/(main)/exchange/page.tsx
  src/app/layout.tsx
Labels: feature

#214 fix: 채팅 메시지 중복 전송 방지 및 Enter 키 전송 기능 추가
  src/app/(main)/chat/_components/ChatMessageInput.tsx
Labels: bug

#218 fix: 로그인 직후에 짠 노하우같은 로그인이 필요한 페이지에 진입하지 못하는 문제 수정 / refactor: 로딩 스피너의 스타일링 방식 변경
  src/app/api/auth/me/route.ts
  src/components/Loading/LoadingSpinner.tsx
  src/components/Loading/SmallLoadinSpinner.tsx
Labels: bug

#224 fix: 짠 소비평가 투표시 에러메시지가 나오는 문제 수정
  src/app/api/votes/[voteId]/like/route.ts
Labels: bug

#228 fix/comment 댓글 중복 제출 방지
  src/app/(main)/boards/_components/Comments/CommentForm.tsx
  src/app/(main)/boards/_components/Comments/CommentItem.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteContent.tsx
  src/app/api/knowhow/[knowhowId]/comments/route.ts
  src/app/api/votes/[voteId]/comments/route.ts
  src/stores/queries/knowhow/comment/useKnowhowCommentMutation.ts
  src/stores/queries/vote/comment/useVoteCommentMutation.ts
Labels: bug, feature

#229 fix: get claim route handler에 revalidatePath 추가
  src/app/api/exchange/[userId]/route.ts
  src/app/api/exchange/claim/[giftId]/route.ts
Labels: bug

#230 feat/fix: 채팅관련 기능 추가 및 디자인 추가입니다.
  src/app/(main)/chat/_components/ChatMessageInput.tsx
  src/app/(main)/chat/_components/ChatMessageItem.tsx
  src/app/(main)/chat/_components/ChatMessageList.tsx
  src/app/(main)/chat/_components/ChatRoomList.tsx
  src/stores/queries/chat/useChatMessagesQuery.ts
  src/stores/queries/chat/useChatRoomsQuery.ts
Labels: feature

#231 Feature/mypage: 회원가입, 로그인, 마이페이지 오류 수정
  src/app/(auth)/login/_components/LoginContainer.tsx
  src/app/(auth)/signUp/_components/EmailForm.tsx
  src/app/(auth)/signUp/_components/NicknameForm.tsx
  src/app/(auth)/signUp/_components/PasswordForm.tsx
  src/app/(auth)/signUp/_components/RecheckPasswordForm.tsx
  src/app/(auth)/signUp/_components/SignUpContainer.tsx
  src/app/(main)/mypage/edit/_components/UserEditPassword.tsx
  src/app/globals.css
  src/components/Modal/NicknameModal.tsx
  src/utils/authValidity.ts
Labels: feature

#234 feat: 사용이 제한된 유저 로그인 막는기능
  src/app/api/auth/login/route.ts
  src/app/api/auth/me/route.ts
Labels: feature

#235 fix: 회원가입 disable 문제 오류 임시방편
  src/app/(auth)/signUp/_components/RecheckPasswordForm.tsx
  src/app/(auth)/signUp/_components/SignUpContainer.tsx
Labels: bug, feature

#236 chore: 회원가입 컴포넌트 콘솔 정리
  src/app/(auth)/signUp/_components/SignUpContainer.tsx
Labels: documentation

#238 feat: 메인페이지 스켈레톤UI 추가
  src/app/(main)/_components/LeftSection/SkeletonKnowhow.tsx
  src/app/(main)/_components/LeftSection/SkeletonVotes.tsx
  src/app/(main)/_components/LeftSection/TopKnowhows.tsx
  src/app/(main)/_components/LeftSection/TopVotes.tsx
  src/app/(main)/_components/RightSection/PointRankingList.tsx
  src/app/(main)/_components/RightSection/SkeletonPointRankingItem.tsx
Labels: feature

#243 fix: 기프티콘 교환시 클라이언트에서 포인트 유효성검사
  src/app/(main)/exchange/_components/GiftItem.tsx
Labels: feature

#248 fix: 유저정보 변경시 유저 refetch
  src/apis/auth.ts
  src/app/(main)/mypage/_components/MypageContainer.tsx
  src/components/Modal/NicknameModal.tsx
  src/provider/contexts/UserContext.tsx
  src/stores/queries/auth/useUserQuery.ts
Labels: feature

#253 fix: 짠 노하우 상세페이지 이미지 핸들링 / refactor: KnowhowEditor 컴포넌트 코드분리
  package-lock.json
  package.json
  src/app/(main)/boards/knowhow/[knowhowId]/_components/PostContent.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowEditor.tsx
  src/app/(main)/boards/knowhow/_hooks/useEditorState.ts
  src/app/(main)/boards/knowhow/_hooks/useFormHandlers.ts
  src/app/(main)/boards/knowhow/_hooks/useFormValidation.ts
  src/app/(main)/boards/knowhow/_hooks/useImageHandler.ts
  src/app/(main)/boards/knowhow/_utils/quillUtils.ts
  src/app/api/votes/[voteId]/like/route.ts
  src/utils/points.ts
Labels: feature

#255 refactor: 짠 소비평가 투표정보 fetch 성능개선
  src/apis/votes.ts
  src/app/(main)/boards/votes/[voteId]/_components/VoteButtons.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteContent.tsx
  src/app/(main)/boards/votes/[voteId]/page.tsx
  src/app/api/auth/login/route.ts
  src/app/api/knowhow/[knowhowId]/like/route.ts
  src/app/api/votes/[voteId]/like/route.ts
  src/stores/queries/vote/like/useVoteLikesQuery.ts
Labels: feature

#256 feat: 메인페이지 반응형 대응, 404 페이지, 퀴즈 관련 수정, 채팅방 관련 수정
  .prettierignore
  public/home/facebook.svg
  public/home/github.svg
  public/home/linked.svg
  public/home/loading.svg
  public/home/youtube.svg
  public/icons/chat/chatRoomBanner.svg
  public/icons/chat/join.svg
  public/icons/home/home.svg
  public/icons/home/knowhow.svg
  public/icons/home/live.svg
  public/icons/home/my.svg
  public/icons/home/view.svg
  public/logos/404Image.svg
  public/logos/footerLogo.svg
  public/logos/tigglemoaAirplane.svg
  src/app/(main)/_components/Footer/Footer.tsx
  src/app/(main)/_components/HeaderContainer.tsx
  src/app/(main)/_components/Nav/NavCategory.tsx
  src/app/(main)/chat/_components/ChatMessageContainer.tsx
  src/app/(main)/chat/_components/ChatMessageInput.tsx
  src/app/(main)/chat/_components/ChatMessageItem.tsx
  src/app/(main)/chat/_components/ChatMessageList.tsx
  src/app/(main)/chat/page.tsx
  src/app/(main)/mypage/_components/Grade/GradeInfo.tsx
  src/app/(main)/quiz/_components/QuizContainer.tsx
  src/app/(main)/quiz/_components/QuizQuestion.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/not-found.tsx
  src/provider/contexts/UserContext.tsx
  src/utils/supabase/middleware.ts
Labels: feature

#257 refactor: usercontext
  src/app/(main)/_components/HeaderContainer.tsx
  src/app/(main)/_components/TopSection/QuizUi.tsx
  src/provider/contexts/UserContext.tsx
Labels: feature

#259 fix: add revalidatePath to login and logout logic
  src/app/(auth)/login/_components/LoginContainer.tsx
  src/app/(main)/_components/HeaderContainer.tsx
  src/app/api/auth/login/route.ts
Labels: bug, feature

#262 Feature/react hook form
  package-lock.json
  package.json
  src/apis/auth.ts
  src/app/(auth)/login/_components/LogInContainer.tsx
  src/app/(auth)/login/_components/LoginContainer.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signUp/_components/EmailForm.tsx
  src/app/(auth)/signUp/_components/NicknameForm.tsx
  src/app/(auth)/signUp/_components/PasswordForm.tsx
  src/app/(auth)/signUp/_components/RecheckPasswordForm.tsx
  src/app/(auth)/signUp/_components/SignUpContainer.tsx
  src/app/(auth)/signUp/_components/TestSignup.tsx
  src/app/(auth)/signUp/page.tsx
  src/app/(auth)/signup/_components/SignUpContainer.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(main)/mypage/edit/_components/UserEditPassword.tsx
  src/app/api/auth/callback/route.ts
  src/app/api/auth/kakao/login/route.ts
  src/app/api/auth/kakao/logout/route.ts
  src/app/api/auth/mypage/nickname/route.ts
  src/app/api/auth/signup/duplication/nickname/route.ts
  src/app/api/auth/signup/duplication/route.ts
  src/app/globals.css
  src/components/Modal/NicknameModal.tsx
  src/types/auth.types.ts
  src/utils/authValidity.ts
Labels: feature

#265 chore: 로그인 컴포넌트 임포트
  src/app/(auth)/login/page.tsx
Labels: documentation

#266 fix: 로그인 컴포넌트 변경
  src/app/(auth)/login/_components/LogInContainer.tsx
Labels: feature

#269 Feature/react hook form : 마이페이지(닉네임변경, 비밀번호변경) react-hook-form 적용하기
  src/apis/auth.ts
  src/app/(auth)/login/_components/LogInContainer.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/_components/SignUpContainer.tsx
  src/app/(main)/mypage/_components/InfoContainer.tsx
  src/app/(main)/mypage/_components/PointContainer.tsx
  src/app/(main)/mypage/edit/_components/EditPassword.tsx
  src/app/(main)/mypage/edit/page.tsx
  src/app/api/auth/mypage/nickname/route.ts
  src/app/globals.css
  src/components/Modal/NicknameModal.tsx
  src/types/auth.types.ts
  src/utils/authValidity.ts
Labels: bug, feature

#272 fix: 짠 소비평가 페이지 캐시관련 버그 수정 / refactor: 페이지네이션 로직 분리
  src/apis/votes.ts
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteButtons.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteContent.tsx
  src/app/(main)/boards/votes/[voteId]/page.tsx
  src/app/(main)/exchange/_components/GiftItem.tsx
  src/app/(main)/mypage/like/_components/LikedKnowhowContainer.tsx
  src/app/(main)/mypage/point/page.tsx
  src/app/(main)/mypage/posts/_components/MyKnowhowContainer.tsx
  src/app/(main)/mypage/posts/_components/MyVotesContainer.tsx
  src/app/api/exchange/claim/[giftId]/route.ts
  src/app/api/exchange/gift/route.ts
  src/app/api/knowhow/my/[userId]/route.ts
  src/app/api/knowhow/route.ts
  src/hooks/usePagination.ts
  src/stores/queries/exchange/useExchangeMutation.ts
  src/stores/queries/vote/like/useVoteLikesQuery.ts
  src/stores/zustand/paginationStore.ts
Labels: bug

#273 Feature/react hook form: 마이페이지(닉네임 변경), 로그인&회원가입 페이지 컴포넌트 통일
  src/app/(main)/mypage/edit/_components/UserEditPassword.tsx
  src/app/(main)/mypage/edit/page.tsx
  src/components/Modal/NicknameModal.tsx
Labels: bug

#278 fix: 짠 노하우 상세페이지에서 작성시간이 다르게 보이는 문제 수정 / 짠 노하우 리스트에서 사용자가 직접 입력한 html 태그의 경우 그대로 보여주도록 수정
  src/app/(main)/boards/_utils/index.ts
  src/app/(main)/boards/knowhow/[knowhowId]/_components/PostContent.tsx
  src/app/(main)/boards/knowhow/_components/Pagination.tsx
  src/app/(main)/boards/knowhow/_components/knowhowItem/KnowhowItem.tsx
Labels: bug

#279 feat: 메인 페이지 디자인 변경 및 반응형 대응
  public/home/KnowhowIcon1.png
  public/home/KnowhowIcon2.png
  public/home/KnowhowIcon3.png
  public/home/Knowhowbg1.png
  public/home/Knowhowbg2.png
  public/home/Knowhowbg3.png
  public/home/banner_mobile.svg
  public/home/crown.svg
  public/home/crown2.png
  public/home/giftIcon.png
  public/home/home_banner.png
  public/home/home_banner.svg
  public/home/home_live_banner.png
  public/home/home_live_banner.svg
  public/home/home_live_enter.svg
  public/home/loading.svg
  public/home/main_live_icon.svg
  public/home/pointEye.png
  public/icons/quiz/animations_confetti 2.gif
  public/icons/quiz/animations_confetti.gif
  public/icons/quiz/back.svg
  src/app/(main)/_components/Header/HeaderContainer.tsx
  src/app/(main)/_components/HeaderContainer.tsx
  src/app/(main)/_components/LeftSection/LeftSection.tsx
  src/app/(main)/_components/LeftSection/LiveChattingBanner.tsx
  src/app/(main)/_components/LeftSection/TopKnowhows.tsx
  src/app/(main)/_components/LeftSection/TopVotes.tsx
  src/app/(main)/_components/Nav/NavCategory.tsx
  src/app/(main)/_components/Nav/NavCategoryMobile.tsx
  src/app/(main)/_components/Nav/NavUserStatus.tsx
  src/app/(main)/_components/Nav/NavUserStatusMoblie.tsx
  src/app/(main)/_components/RightSection/PointBanner.tsx
  src/app/(main)/_components/RightSection/PointRankingContainer.tsx
  src/app/(main)/_components/RightSection/PointRankingItem.tsx
  src/app/(main)/_components/RightSection/PointRankingList.tsx
  src/app/(main)/_components/RightSection/RightSection.tsx
  src/app/(main)/_components/RightSection/SkeletonPointRankingItem.tsx
  src/app/(main)/_components/TopSection/QuizUi.tsx
  src/app/(main)/_components/TopSection/TopBanner.tsx
  src/app/(main)/_components/TopSection/TopSection.tsx
  src/app/(main)/page.tsx
  src/app/(main)/quiz/_components/QuizAnswer.tsx
  src/app/(main)/quiz/_components/QuizContainer.tsx
  src/app/(main)/quiz/_components/QuizModal.tsx
  src/app/(main)/quiz/_components/QuizQuestion.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/Button/Button.tsx
  src/components/Modal/BackDrop.tsx
Labels: feature

#280 feat: 메인페이지 반응형 대응 추가
  public/home/KnowhowIcon1.png
  public/home/KnowhowIcon2.png
  public/home/KnowhowIcon3.png
  public/home/banner_mobile.png
  public/home/banner_mobile.svg
  public/home/banner_mobile2.png
  public/home/banner_mobile3.png
  public/home/home_banner.png
  public/home/home_banner.svg
  public/home/home_banner2.png
  public/home/home_banner3.png
  public/home/home_banner_card.png
  public/home/moachar.png
  public/home/taesanchar.png
  public/home/tigglechar.png
  public/home/zzanFamilyIcon.png
  src/app/(main)/_components/Header/HeaderContainer.tsx
  src/app/(main)/_components/LeftSection/TopKnowhows.tsx
  src/app/(main)/_components/Nav/NavUserStatusMoblie.tsx
  src/app/(main)/_components/RightSection/Introduction.tsx
  src/app/(main)/_components/RightSection/Magazine.tsx
  src/app/(main)/_components/RightSection/RightSection.tsx
  src/app/(main)/_components/TopSection/QuizUi.tsx
  src/app/(main)/_components/TopSection/TopBanner.tsx
Labels: feature

#286 fix/vote-web-ui 웹 UI 수정
  public/icons/mypage/cheering.png
  public/icons/mypage/shopping.png
  public/icons/vote/vote_list_image.png
  src/app/(main)/boards/_components/Comments/CommentActions.tsx
  src/app/(main)/boards/_components/Comments/CommentEditForm.tsx
  src/app/(main)/boards/_components/Comments/CommentForm.tsx
  src/app/(main)/boards/_components/Comments/CommentItem.tsx
  src/app/(main)/boards/_components/Comments/CommentsContainer.tsx
  src/app/(main)/boards/_components/Comments/CommentsList.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteContent.tsx
  src/app/(main)/boards/votes/[voteId]/page.tsx
  src/app/(main)/boards/votes/_components/BoardDescription.tsx
  src/app/(main)/boards/votes/_components/SkeletonVoteItem.tsx
  src/app/(main)/boards/votes/_components/SkeletonVoteList.tsx
  src/app/(main)/boards/votes/_components/VoteItem.tsx
  src/app/(main)/boards/votes/_components/VoteWriteForm.tsx
  src/app/(main)/boards/votes/_components/VotesContainer.tsx
  src/app/(main)/boards/votes/_components/VotesList.tsx
  src/app/(main)/boards/votes/page.tsx
  src/app/(main)/mypage/_components/Points/MyCurrentPoints.tsx
  src/app/(main)/mypage/_components/Points/MyPointsHistoryTable.tsx
  src/app/(main)/mypage/point/page.tsx
Labels: bug, feature

#289 Moblie/auth: 로그인 페이지 카카오 이미지 오류 해결, 마이페이지(등급제) 모바일 반응형 구축(1)
  src/app/(auth)/login/_components/LogInContainer.tsx
  src/app/(main)/mypage/_components/Grade/GradeInfo.tsx
  src/app/(main)/mypage/_components/Grade/GradeInfoContainer.tsx
  src/app/(main)/mypage/_components/Grade/GradeModal.tsx
Labels: bug, feature

#290 추가 기능 업데이트
  package-lock.json
  public/description_images/knowhow_mobile.png
  public/description_images/knowhow_web.png
  public/icons/empty_heart.svg
  public/icons/filled_heart.svg
  public/icons/filter/search.png
  public/icons/filter/search_mobile.svg
  public/icons/filter/search_web.svg
  public/icons/mypage/cheering.png
  public/icons/mypage/shopping.png
  public/icons/vote/vote_list_image.png
  src/app/(auth)/login/_components/LogInContainer.tsx
  src/app/(main)/boards/_components/Comments/CommentActions.tsx
  src/app/(main)/boards/_components/Comments/CommentEditForm.tsx
  src/app/(main)/boards/_components/Comments/CommentForm.tsx
  src/app/(main)/boards/_components/Comments/CommentItem.tsx
  src/app/(main)/boards/_components/Comments/CommentsContainer.tsx
  src/app/(main)/boards/_components/Comments/CommentsList.tsx
  src/app/(main)/boards/knowhow/_components/DescriptionTagList.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowDescription.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowEditor.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowFilter.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowList.tsx
  src/app/(main)/boards/knowhow/_components/Pagination.tsx
  src/app/(main)/boards/knowhow/_components/SearchOptions.tsx
  src/app/(main)/boards/knowhow/_components/knowhowItem/KnowhowItem.tsx
  src/app/(main)/boards/knowhow/_constants/index.ts
  src/app/(main)/boards/knowhow/_hooks/useFormValidation.ts
  src/app/(main)/boards/knowhow/page.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteContent.tsx
  src/app/(main)/boards/votes/[voteId]/page.tsx
  src/app/(main)/boards/votes/_components/BoardDescription.tsx
  src/app/(main)/boards/votes/_components/SkeletonVoteItem.tsx
  src/app/(main)/boards/votes/_components/SkeletonVoteList.tsx
  src/app/(main)/boards/votes/_components/VoteItem.tsx
  src/app/(main)/boards/votes/_components/VoteWriteForm.tsx
  src/app/(main)/boards/votes/_components/VotesContainer.tsx
  src/app/(main)/boards/votes/_components/VotesList.tsx
  src/app/(main)/boards/votes/page.tsx
  src/app/(main)/mypage/_components/Grade/GradeInfo.tsx
  src/app/(main)/mypage/_components/Grade/GradeInfoContainer.tsx
  src/app/(main)/mypage/_components/Grade/GradeModal.tsx
  src/app/(main)/mypage/_components/Points/MyCurrentPoints.tsx
  src/app/(main)/mypage/_components/Points/MyPointsHistoryTable.tsx
  src/app/(main)/mypage/point/page.tsx
  src/components/DescriptionTagItem.tsx
  src/hooks/useIsWideScreen.ts
  tailwind.config.ts
Labels: feature

#298 feat: 짠 노하우 상세페이지 모바일에서 노하우 리스트 렌더링
  src/app/(main)/boards/_components/Divider.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/page.tsx
  src/app/(main)/boards/knowhow/_components/ConditionalKnowhowContainer.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowFilter.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowList.tsx
  src/app/(main)/boards/knowhow/_components/SearchOptions.tsx
  src/app/(main)/boards/knowhow/_components/SkeletonKnowhowList.tsx
  src/app/(main)/boards/knowhow/_components/knowhowItem/KnowhowItem.tsx
  src/app/(main)/boards/knowhow/_constants/index.ts
  src/app/(main)/mypage/like/_components/LikedKnowhowContainer.tsx
  src/app/(main)/mypage/posts/_components/MyKnowhowContainer.tsx
  src/components/MobileHeader.tsx
  src/hooks/useIsWideScreen.ts
  src/stores/queries/knowhow/post/useKnowhowMutation.ts
Labels: feature

#303 feat/vote-mobile-ui 모바일 UI 구현
  public/icons/vote/vote_write_button.png
  public/icons/vote/vote_write_button_hover.png
  src/app/(main)/boards/_components/Comments/CommentsContainer.tsx
  src/app/(main)/boards/votes/[voteId]/_components/ActionNav.tsx
  src/app/(main)/boards/votes/[voteId]/_components/NavButton.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteButtons.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteContent.tsx
  src/app/(main)/boards/votes/[voteId]/page.tsx
  src/app/(main)/boards/votes/_components/BoardDescription.tsx
  src/app/(main)/boards/votes/_components/SkeletonVoteItem.tsx
  src/app/(main)/boards/votes/_components/SkeletonVoteList.tsx
  src/app/(main)/boards/votes/_components/SortButtons.tsx
  src/app/(main)/boards/votes/_components/VoteDescription.tsx
  src/app/(main)/boards/votes/_components/VoteItem.tsx
  src/app/(main)/boards/votes/_components/VoteWriteForm.tsx
  src/app/(main)/boards/votes/_components/VotesContainer.tsx
  src/app/(main)/boards/votes/_components/VotesList.tsx
  src/app/(main)/boards/votes/edit/[voteId]/page.tsx
  src/app/(main)/boards/votes/page.tsx
  src/app/(main)/boards/votes/write/page.tsx
  src/app/(main)/mypage/_components/Points/MyCurrentPoints.tsx
  src/app/(main)/mypage/_components/Points/MyPointsHistoryTable.tsx
  src/app/(main)/mypage/point/page.tsx
Labels: feature

#308 feat: 기프티콘 신청내역 페이지네이션 적용 / design: 포인트샵 페이지 웹 및 모바일 UI
  public/description_images/exchange.png
  src/apis/exchange.ts
  src/app/(main)/boards/knowhow/_components/KnowhowDescription.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowEditorContainer.tsx
  src/app/(main)/boards/knowhow/_components/knowhowItem/KnowhowItem.tsx
  src/app/(main)/exchange/_components/ClaimContainer.tsx
  src/app/(main)/exchange/_components/ClaimItem.tsx
  src/app/(main)/exchange/_components/ClaimList.tsx
  src/app/(main)/exchange/_components/ExchangeContainer.tsx
  src/app/(main)/exchange/_components/ExchangeDescription.tsx
  src/app/(main)/exchange/_components/GiftContainer.tsx
  src/app/(main)/exchange/_components/GiftItem.tsx
  src/app/(main)/exchange/_components/GiftList.tsx
  src/app/(main)/exchange/_constants/index.ts
  src/app/(main)/exchange/page.tsx
  src/app/(main)/mypage/like/_components/LikedKnowhowContainer.tsx
  src/app/(main)/mypage/posts/_components/FilterOption.tsx
  src/app/(main)/mypage/posts/_components/MyKnowhowContainer.tsx
  src/app/(main)/mypage/posts/_components/MyPostsContainer.tsx
  src/app/(main)/mypage/posts/_components/MyVotesContainer.tsx
  src/app/(main)/mypage/posts/_components/NoPostsMessage.tsx
  src/app/(main)/mypage/posts/page.tsx
  src/app/api/exchange/[userId]/route.ts
  src/app/api/knowhow/route.ts
  src/components/DescriptionTagItem.tsx
  src/stores/queries/exchange/useClaimsQuery.ts
  src/types/exchange.type.ts
Labels: feature

#311 feat: pwa 설정 및 추가, 등급제 페이지 수정
  .gitignore
  next.config.mjs
  package-lock.json
  package.json
  public/icons/pwa/144.png
  public/icons/pwa/180.png
  public/icons/pwa/192.png
  public/icons/pwa/256.png
  public/icons/pwa/32.png
  public/icons/pwa/512.png
  public/icons/pwa/60.png
  public/icons/pwa/72.png
  public/icons/pwa/96.png
  public/manifest.json
  src/app/(main)/_components/Footer/ConditionalFooter.tsx
  src/app/(main)/_components/LeftSection/TopVotes.tsx
  src/app/(main)/_components/Nav/NavCategoryMobile.tsx
  src/app/(main)/_components/TopSection/TopBanner.tsx
  src/app/(main)/mypage/_components/Grade/GradeInfo.tsx
  src/app/(main)/mypage/_components/Grade/GradeInfoContainer.tsx
  src/app/(main)/mypage/_components/Grade/GradeModal.tsx
  src/app/(main)/mypage/_components/Grade/GradeTitleMobile.tsx
  src/app/(main)/mypage/_components/MypageContainer.tsx
  src/app/layout.tsx
  src/utils/supabase/middleware.ts
  supabase/.gitignore
Labels: feature

#313 design: 짠 노하우 리스트 UI 수정 / feat: OG 메타데이터 추가 등
  public/icons/filter/arrow_down.svg
  public/open_graph_img.png
  src/app/(main)/boards/knowhow/[knowhowId]/page.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/boards/knowhow/_components/Pagination.tsx
  src/app/(main)/boards/knowhow/_components/SearchOptions.tsx
  src/app/(main)/boards/knowhow/page.tsx
  src/app/(main)/boards/votes/[voteId]/page.tsx
  src/app/(main)/boards/votes/page.tsx
  src/app/(main)/chat/page.tsx
  src/app/(main)/exchange/page.tsx
  src/app/layout.tsx
  src/constants/index.ts
Labels: feature

#305 Fix/moblie/auth : 마이페이지, 로그인, 회원가입 모바일 반응형 UI 구축 및 추가 기능
  public/badges/lv1.png
  public/badges/lv2.png
  public/badges/lv3.png
  public/badges/lv4.png
  public/badges/lv5.png
  src/app/(auth)/login/_components/LogInContainer.tsx
  src/app/(auth)/signup/_components/SignUpContainer.tsx
  src/app/(main)/mypage/_components/InfoContainer.tsx
  src/app/(main)/mypage/_components/MypageContainer.tsx
  src/app/(main)/mypage/_components/PointContainer.tsx
  src/app/(main)/mypage/edit/_components/EditPassword.tsx
  src/app/globals.css
  src/components/Modal/NicknameModal.tsx
Labels: feature

#315 feat/vote-performance-optimization UI 수정 및 리팩토링
  public/icons/vote/vote_list_image_mobile.png
  src/app/(main)/boards/votes/[voteId]/_components/ActionNav.tsx
  src/app/(main)/boards/votes/[voteId]/_components/NavButton.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteButtons.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteContent.tsx
  src/app/(main)/boards/votes/_components/SkeletonVoteItem.tsx
  src/app/(main)/boards/votes/_components/SkeletonVoteList.tsx
  src/app/(main)/boards/votes/_components/SortButtons.tsx
  src/app/(main)/boards/votes/_components/VoteDescription.tsx
  src/app/(main)/boards/votes/_components/VoteItem.tsx
  src/app/(main)/boards/votes/_components/VoteWriteForm.tsx
  src/app/(main)/boards/votes/_components/VotesContainer.tsx
  src/app/(main)/boards/votes/_components/VotesList.tsx
  src/app/(main)/boards/votes/edit/[voteId]/page.tsx
  src/app/(main)/boards/votes/page.tsx
  src/app/(main)/mypage/_components/Points/MyCurrentPoints.tsx
  src/app/(main)/mypage/_components/Points/MyPointsHistoryTable.tsx
Labels: bug, feature

#322 feat: 짠 노하우 상세페이지 모바일 하단 리스트 더보기 방식으로 변경
  src/apis/knowhow.ts
  src/app/(main)/boards/knowhow/[knowhowId]/page.tsx
  src/app/(main)/boards/knowhow/_components/ConditionalKnowhowContainer.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowList.tsx
  src/app/(main)/boards/knowhow/_components/knowhowItem/KnowhowItem.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteButtons.tsx
  src/app/(main)/boards/votes/_components/VotesList.tsx
  src/app/api/knowhow/[knowhowId]/previous/route.ts
  src/stores/queries/knowhow/post/usePreviousKnowhowsQuery.ts
  src/types/knowhow.type.ts
  src/types/supabase.ts
Labels: feature

#319 Fix/auth: 로그인, 회원가입, 마이페이지 - metadata 추가, MobileHeader 추가, any 타입 수정 / 헤더 포인트 추가
  public/badges/lv1.png
  public/badges/lv2.png
  public/badges/lv3.png
  public/badges/lv4.png
  public/badges/lv5.png
  public/icons/mypage/coin.png
  public/icons/mypage/lv1.png
  public/icons/mypage/lv2.png
  public/icons/mypage/lv3.png
  public/icons/mypage/lv4.png
  public/icons/mypage/lv5.png
  src/app/(auth)/login/_components/LogInContainer.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/_components/SignUpContainer.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(main)/_components/Header/HeaderContainer.tsx
  src/app/(main)/_components/Nav/NavUserStatus.tsx
  src/app/(main)/mypage/_components/LevelContainer.tsx
  src/app/(main)/mypage/_components/MypageContainer.tsx
  src/app/(main)/mypage/_components/PointContainer.tsx
  src/app/(main)/mypage/edit/_components/EditPassword.tsx
  src/app/(main)/mypage/edit/page.tsx
  src/app/(main)/mypage/page.tsx
  src/app/api/auth/login/route.ts
  src/components/Modal/NicknameModal.tsx
  src/provider/contexts/UserContext.tsx
Labels: feature

#323 fix: 마이페이지 사용가능-누적포인트 간격 조정
  src/app/(main)/mypage/_components/PointContainer.tsx
Labels: feature

#324 feat/comment 댓글 더보기 기능
  src/apis/knowhow.ts
  src/apis/votes.ts
  src/app/(main)/boards/_components/Comments/CommentForm.tsx
  src/app/(main)/boards/_components/Comments/CommentsContainer.tsx
  src/app/(main)/boards/_components/Comments/CommentsList.tsx
  src/app/api/knowhow/[knowhowId]/comments/route.ts
  src/app/api/votes/[voteId]/comments/route.ts
  src/stores/queries/knowhow/comment/useKnowhowCommentsQuery.ts
  src/stores/queries/vote/comment/useVoteCommentsQuery.ts
  src/types/knowhow.type.ts
  src/types/vote.type.ts
Labels: feature

#326 feat/vote-detail-mobile 짠 소비 더보기 기능
  src/apis/votes.ts
  src/app/(main)/boards/_components/Comments/CommentItem.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteContent.tsx
  src/app/(main)/boards/votes/[voteId]/page.tsx
  src/app/(main)/boards/votes/_components/ConditionalVoteContainer.tsx
  src/app/(main)/boards/votes/_components/VotesList.tsx
  src/app/api/votes/[voteId]/route.ts
  src/app/api/votes/posts/route.ts
  src/stores/queries/vote/post/useVotesQuery.ts
  src/types/vote.type.ts
Labels: feature

#327 feat: 로딩 이미지 변경 , 유저 규제 처리 게시글 규제 처리
  public/blocked/sad_tikkle-detail.png
  public/blocked/sad_tikkle.png
  public/flying_tikkle.gif
  public/icons/coin.svg
  public/icons/point.png
  src/apis/auth.ts
  src/app/(auth)/login/_components/BlockedUserError.tsx
  src/app/(auth)/login/_components/LogInContainer.tsx
  src/app/(auth)/login/blocked/page.tsx
  src/app/(main)/boards/_components/BlockedPost.tsx
  src/app/(main)/boards/_components/Comments/CommentItem.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/loading.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/page.tsx
  src/app/(main)/boards/knowhow/_components/ConditionalKnowhowContainer.tsx
  src/app/(main)/boards/knowhow/_components/knowhowItem/KnowhowItem.tsx
  src/app/(main)/boards/votes/[voteId]/loading.tsx
  src/app/(main)/boards/votes/[voteId]/page.tsx
  src/app/(main)/boards/votes/_components/BlockedVoteItem.tsx
  src/app/(main)/boards/votes/_components/VoteItem.tsx
  src/app/(main)/exchange/_components/ClaimContainer.tsx
  src/app/(main)/exchange/_components/GiftItem.tsx
  src/app/(main)/mypage/_components/Grade/GradeInfo.tsx
  src/app/(main)/mypage/_components/PointContainer.tsx
  src/app/(main)/mypage/_components/Points/MyPointsHistoryTable.tsx
  src/app/api/auth/callback/route.ts
  src/app/api/exchange/[userId]/route.ts
  src/app/api/votes/posts/route.ts
  src/components/Loading/FlyingTikkle.tsx
  src/components/MobileHeader.tsx
  src/types/supabase.ts
Labels: feature

#334 fix: 로딩 이미지 변경 / feat: middleware redirection 설정 등 자잘한 수정
  public/loading/flying_tikkle.gif
  public/open_graph_img.png
  public/open_graph_img_old.png
  src/apis/auth.ts
  src/app/(auth)/login/_components/LogInContainer.tsx
  src/app/(main)/boards/_components/Comments/CommentForm.tsx
  src/app/(main)/boards/_components/Comments/CommentItem.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/page.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowDescription.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowEditor.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowEditorContainer.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowList.tsx
  src/app/(main)/boards/knowhow/_components/SkeletonKnowhowList.tsx
  src/app/(main)/boards/knowhow/page.tsx
  src/app/(main)/boards/votes/_components/SkeletonVoteList.tsx
  src/app/(main)/boards/votes/_components/VoteItem.tsx
  src/app/(main)/boards/votes/_components/VoteWriteForm.tsx
  src/app/(main)/chat/[roomId]/page.tsx
  src/app/(main)/chat/_components/ChatMessageList.tsx
  src/app/(main)/exchange/_components/ClaimContainer.tsx
  src/app/(main)/exchange/_components/GiftContainer.tsx
  src/app/(main)/exchange/_components/GiftItem.tsx
  src/app/(main)/exchange/loading.tsx
  src/app/(main)/mypage/_components/MypageContainer.tsx
  src/app/(main)/mypage/_components/Points/MyPointsHistoryTable.tsx
  src/app/(main)/mypage/point/loading.tsx
  src/app/(main)/mypage/posts/_components/FilterOption.tsx
  src/app/(main)/quiz/_components/QuizContainer.tsx
  src/app/api/auth/callback/route.ts
  src/app/api/auth/login/route.ts
  src/app/api/knowhow/[knowhowId]/previous/route.ts
  src/app/globals.css
  src/app/layout.tsx
  src/components/Button/Button_old.tsx
  src/components/Loading/FlyingTikkle.tsx
  src/components/Loading/SmallLoadinSpinner.tsx
  src/components/Modal/DefaultModalTemplate.tsx
  src/components/Modal/Modal.tsx
  src/provider/contexts/UserContext.tsx
  src/stores/queries/exchange/useClaimsQuery.ts
  src/stores/queries/exchange/useExchangeMutation.ts
  src/stores/queries/knowhow/comment/useKnowhowCommentsQuery.ts
  src/stores/queries/knowhow/post/useMyKnowhowsQuery.ts
  src/stores/queries/useTopKnowhowQuery.ts
  src/stores/queries/useTopVotesQuery.ts
  src/stores/queries/vote/comment/useVoteCommentsQuery.ts
  src/stores/queries/vote/post/useMyVotesQuery.ts
  src/utils/points.ts
  src/utils/supabase/middleware.ts
Labels: bug, feature

#336 docs: readme 최종 수정
  README.md
Labels: documentation

#337 chore: dev => main
  README.md
  public/loading/flying_tikkle.gif
  public/open_graph_img.png
  public/open_graph_img_old.png
  src/apis/auth.ts
  src/app/(auth)/login/_components/LogInContainer.tsx
  src/app/(main)/boards/_components/Comments/CommentForm.tsx
  src/app/(main)/boards/_components/Comments/CommentItem.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowDescription.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowEditor.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowEditorContainer.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowList.tsx
  src/app/(main)/boards/knowhow/_components/SkeletonKnowhowList.tsx
  src/app/(main)/boards/knowhow/page.tsx
  src/app/(main)/boards/votes/_components/SkeletonVoteList.tsx
  src/app/(main)/boards/votes/_components/VoteItem.tsx
  src/app/(main)/boards/votes/_components/VoteWriteForm.tsx
  src/app/(main)/chat/[roomId]/page.tsx
  src/app/(main)/chat/_components/ChatMessageList.tsx
  src/app/(main)/exchange/_components/ClaimContainer.tsx
  src/app/(main)/exchange/_components/GiftContainer.tsx
  src/app/(main)/exchange/_components/GiftItem.tsx
  src/app/(main)/exchange/loading.tsx
  src/app/(main)/mypage/_components/MypageContainer.tsx
  src/app/(main)/mypage/_components/Points/MyPointsHistoryTable.tsx
  src/app/(main)/mypage/point/loading.tsx
  src/app/(main)/mypage/posts/_components/FilterOption.tsx
  src/app/(main)/quiz/_components/QuizContainer.tsx
  src/app/api/auth/callback/route.ts
  src/app/api/auth/login/route.ts
  src/app/api/knowhow/[knowhowId]/previous/route.ts
  src/app/globals.css
  src/app/layout.tsx
  src/components/Button/Button_old.tsx
  src/components/Loading/FlyingTikkle.tsx
  src/components/Loading/SmallLoadinSpinner.tsx
  src/components/Modal/DefaultModalTemplate.tsx
  src/components/Modal/Modal.tsx
  src/provider/contexts/UserContext.tsx
  src/stores/queries/exchange/useClaimsQuery.ts
  src/stores/queries/exchange/useExchangeMutation.ts
  src/stores/queries/knowhow/comment/useKnowhowCommentsQuery.ts
  src/stores/queries/knowhow/post/useMyKnowhowsQuery.ts
  src/stores/queries/useTopKnowhowQuery.ts
  src/stores/queries/useTopVotesQuery.ts
  src/stores/queries/vote/comment/useVoteCommentsQuery.ts
  src/stores/queries/vote/post/useMyVotesQuery.ts
  src/utils/checkPoints.ts
  src/utils/points.ts
  src/utils/supabase/middleware.ts
Labels: feature
