Repository ZZANTech/ZZANTech-Fe, pull requests merged in 2024-07, with the labels that each got.

#10 config: login 폴더, _componenets 폴더 생성
  src/app/login/_components/LoginForm.tsx
  src/app/login/page.tsx
Labels: feature

#15 feat: knowhow 목록 페이지
  package-lock.json
  package.json
  src/apis/knowhow.ts
  src/app/(main)/boards/knowhow/[knowhowId]/page.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowFilter.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowItem.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowList.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowPagination.tsx
  src/app/(main)/boards/knowhow/_components/SearchOptions.tsx
  src/app/(main)/boards/knowhow/_components/SortOptions.tsx
  src/app/(main)/boards/knowhow/_constants/index.ts
  src/app/(main)/boards/knowhow/page.tsx
  src/app/api/auth/route.ts
  src/app/api/knowhow/posts/route.ts
  src/components/Button/Button.tsx
  src/constants/index.ts
  src/store/queries/useKnowhowsQuery.ts
  src/types/knowhow.type.ts
  src/types/supabase.ts
  src/utils/supabase/server.ts
Labels: feature

#19 feat: 짠 노하우 상세페이지 조회
  src/apis/knowhow.ts
  src/app/(main)/boards/_components/Comments/CommentForm.tsx
  src/app/(main)/boards/_components/Comments/CommentItem.tsx
  src/app/(main)/boards/_components/Comments/CommentsContainer.tsx
  src/app/(main)/boards/_components/Comments/CommentsList.tsx
  src/app/(main)/boards/_utils/index.ts
  src/app/(main)/boards/knowhow/[knowhowId]/_components/ActionNav.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/_components/KnowhowLikes.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/_components/PostActions.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/_components/PostContent.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/page.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/api/knowhow/comments/[knowhowId]/route.ts
  src/app/api/knowhow/posts/[knowhowId]/route.ts
  src/components/Button/Button.tsx
  src/store/queries/useCommentsQuery.ts
  src/store/queries/useKnowhowQuery.ts
  src/types/knowhow.type.ts
Labels: feature

#20 feat: login & signup UI 완성
  src/app/(user)/auth/page.tsx
  src/app/(user)/login/_components/LoginForm.tsx
  src/app/(user)/login/page.tsx
  src/app/(user)/mypage/page.tsx
  src/app/(user)/signUp/_components/SignUpForm.tsx
  src/app/(user)/signUp/page.tsx
  src/app/login/_components/LoginForm.tsx
Labels: feature

#22 feat/fetch-vote-list 소비 평가 목록 표시
  src/apis/votes.ts
  src/app/(main)/boards/votes/_components/VoteItem.tsx
  src/app/(main)/boards/votes/_components/VotesContainer.tsx
  src/app/(main)/boards/votes/_components/VotesList.tsx
  src/app/api/votes/posts/route.ts
  src/store/queries/useVotesQuery.ts
  src/types/supabase.ts
  src/types/vote.type.ts
Labels: feature

#25 feat/signup 회원가입 페이지 - signup 연동, 컴포넌트 분리, 중복확인, 유효성검사
  package-lock.json
  package.json
  src/app/(user)/login/_components/LoginForm.tsx
  src/app/(user)/signUp/_components/EmailForm.tsx
  src/app/(user)/signUp/_components/NicknameForm.tsx
  src/app/(user)/signUp/_components/PasswordForm.tsx
  src/app/(user)/signUp/_components/RecheckPasswordForm.tsx
  src/app/(user)/signUp/_components/SignUpForm.tsx
  src/utils/supabase/client.ts
Labels: feature

#27 feat: 짠 노하우 댓글 작성기능 및 텍스트 에디터
  next.config.mjs
  package-lock.json
  package.json
  src/apis/knowhow.ts
  src/app/(main)/boards/_components/Comments/CommentForm.tsx
  src/app/(main)/boards/_components/Comments/CommentsContainer.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowEditor.tsx
  src/app/(main)/boards/knowhow/edit/page.tsx
  src/app/api/knowhow/comments/[knowhowId]/route.ts
  src/app/api/knowhow/image/route.config.ts
  src/app/api/knowhow/image/route.ts
  src/store/queries/useKnowhowCommentMutation.ts
  src/store/queries/useKnowhowCommentsQuery.ts
  src/store/queries/useKnowhowImageMutation.ts
  src/types/knowhow.type.ts
  tailwind.config.ts
Labels: feature

#28 feat: 짠 노하우 작성 / 및 리스트와 상세페이지 렌더링로직 수정
  next.config.mjs
  src/apis/knowhow.ts
  src/app/(main)/boards/knowhow/[knowhowId]/_components/PostContent.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowEditor.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowItem.tsx
  src/app/api/knowhow/image/route.ts
  src/app/api/knowhow/posts/route.ts
  src/store/queries/useKnowhowMutation.ts
  src/types/knowhow.type.ts
  src/types/supabase.ts
Labels: feature

#30 Feature/quiz 퀴즈 기능 추가 및 pointCheck 함수 추가
  package-lock.json
  package.json
  src/apis/quiz.ts
  src/app/(main)/@modal/(.)quiz/page.tsx
  src/app/(main)/@modal/default.tsx
  src/app/(main)/boards/_components/Comments/CommentsContainer.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/page.tsx
  src/app/(main)/quiz/_components/QuizAnswer.tsx
  src/app/(main)/quiz/_components/QuizContainer.tsx
  src/app/(main)/quiz/_components/QuizModal.tsx
  src/app/(main)/quiz/_components/QuizQuestion.tsx
  src/app/(main)/quiz/page.tsx
  src/app/(user)/layout.tsx
  src/app/api/quiz/route.ts
  src/app/api/quiz/submit/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/store/zustand/index.ts
  src/stores/queries/useCommentsQuery.ts
  src/stores/queries/useKnowhowQuery.ts
  src/stores/queries/useKnowhowsQuery.ts
  src/stores/queries/useQuizQuery.ts
  src/stores/queries/useSubmitAnswer.ts
  src/stores/zustand/quizStore.ts
  src/types/answer.type.ts
  src/types/quiz.type.ts
  src/types/supabase.ts
  src/types/user.type.ts
  src/utils/checkPoints.ts
  supabase/.gitignore
  supabase/config.toml
  supabase/seed.sql
Labels: feature

#34 feat: 짠노하우 댓글 수정 및 삭제
  src/apis/knowhow.ts
  src/app/(main)/boards/_components/Comments/CommentItem.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/_components/PostContent.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowEditor.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowItem.tsx
  src/app/api/knowhow/[knowhowId]/comments/route.ts
  src/app/api/knowhow/[knowhowId]/route.ts
  src/app/api/knowhow/comments/[commentId]/route.ts
  src/app/api/knowhow/route.ts
  src/stores/queries/useKnowhowCommentMutation.ts
  src/types/knowhow.type.ts
  src/types/supabase.ts
Labels: feature

#37 feat: header UI 뼈대 완료
  .github/PULL_REQUEST_TEMPLATE.md
  src/app/(main)/_components/HeaderContainer.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/mypage/page.tsx
  src/app/(main)/myprofile/page.tsx
  src/app/globals.css
  src/assets/logo.png
  src/assets/myprofileLogo.png
Labels: feature

#41 feat: 게시글 수정,삭제 / 댓글 수정,삭제
  src/apis/knowhow.ts
  src/app/(main)/boards/knowhow/[knowhowId]/_components/ActionNav.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/_components/PostActions.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/_components/PostContent.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/page.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowEditor.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowFilter.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowItem.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowPagination.tsx
  src/app/(main)/boards/knowhow/_components/SearchOptions.tsx
  src/app/(main)/boards/knowhow/_constants/index.ts
  src/app/(main)/boards/knowhow/edit/[knowhowId]/page.tsx
  src/app/(main)/boards/knowhow/write/page.tsx
  src/app/api/knowhow/[knowhowId]/route.ts
  src/app/api/quiz/route.ts
  src/app/layout.tsx
  src/stores/queries/useKnowhowCommentMutation.ts
  src/stores/queries/useKnowhowMutation.ts
Labels: feature

#42 feat/vote-detail 짠 소비 평가 상세 정보 표시
  src/apis/votes.ts
  src/app/(main)/boards/votes/[voteId]/_components/VoteContent.tsx
  src/app/(main)/boards/votes/[voteId]/page.tsx
  src/app/(main)/boards/votes/_components/VoteItem.tsx
  src/app/api/votes/[voteId]/route.ts
  src/types/supabase.ts
Labels: feature

#45 feat/create-vote 짠 소비 등록 UI 제작
  src/app/(main)/boards/votes/_components/VoteWriteForm.tsx
  src/app/(main)/boards/votes/_components/VotesContainer.tsx
  src/app/(main)/boards/votes/write/page.tsx
Labels: feature

#46 feat: 유저 상태 관리
  package-lock.json
  src/app/(auth)/login/_components/LoginContainer.tsx
  src/app/(auth)/login/_components/LoginEmailForm.tsx
  src/app/(auth)/login/_components/LoginPasswordForm.tsx
  src/app/(auth)/signUp/_components/EmailForm.tsx
  src/app/(auth)/signUp/_components/NicknameForm.tsx
  src/app/(auth)/signUp/_components/PasswordForm.tsx
  src/app/(auth)/signUp/_components/RecheckPasswordForm.tsx
  src/app/(auth)/signUp/_components/SignUpContainer.tsx
  src/app/(main)/_components/HeaderContainer.tsx
  src/app/(main)/mypage/page.tsx
  src/app/(main)/myprofile/page.tsx
  src/app/api/auth/login/route.ts
  src/app/api/auth/me/route.ts
  src/app/api/auth/signup/route.ts
  src/app/layout.tsx
  src/provider/UserProvider.tsx
Labels: bug, feature

#49 feat: 공용 모달
  src/app/(main)/boards/_components/Comments/CommentItem.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/_components/ActionNav.tsx
  src/app/layout.tsx
  src/components/Modal/AlertModal.tsx
  src/components/Modal/BackDrop.tsx
  src/components/Modal/ConfirmModal.tsx
  src/components/Modal/Modal.tsx
  src/provider/Providers.tsx
  src/provider/contexts/modalContext.tsx
  src/types/modal.type.ts
Labels: feature

#55 feat/create-vote 짠 소비 등록
  src/apis/votes.ts
  src/app/(main)/boards/votes/_components/VoteWriteForm.tsx
  src/app/(main)/boards/votes/_components/VotesContainer.tsx
  src/app/api/votes/posts/route.ts
  src/stores/queries/useVoteMutation.ts
Labels: feature

#62 feat: knowhow 관련기능 유저 연동
  .vscode/settings.json
  src/app/(main)/boards/_components/Comments/CommentActions.tsx
  src/app/(main)/boards/_components/Comments/CommentEditForm.tsx
  src/app/(main)/boards/_components/Comments/CommentForm.tsx
  src/app/(main)/boards/_components/Comments/CommentItem.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/_components/ActionNav.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/_components/PostActions.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/page.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowEditor.tsx
Labels: feature

#63 Feature 채팅 기능 구현
  commitlint.config.js
  src/apis/chat.ts
  src/apis/quiz.ts
  src/app/(main)/_components/HeaderContainer.tsx
  src/app/(main)/chat/[roomId]/page.tsx
  src/app/(main)/chat/_components/ChatMessageContainer.tsx
  src/app/(main)/chat/_components/ChatMessageInput.tsx
  src/app/(main)/chat/_components/ChatMessageItem.tsx
  src/app/(main)/chat/_components/ChatMessageList.tsx
  src/app/(main)/chat/_components/ChatRoomList.tsx
  src/app/(main)/chat/_utils/subscribeToChannel.ts
  src/app/(main)/chat/_utils/useRealtimeChats.tsx
  src/app/(main)/chat/page.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/page.tsx
  src/app/(main)/quiz/_components/QuizAnswer.tsx
  src/app/(main)/quiz/_components/QuizContainer.tsx
  src/app/(main)/quiz/_components/QuizQuestion.tsx
  src/app/(main)/quiz/page.tsx
  src/app/(user)/layout.tsx
  src/app/api/chat/route.ts
  src/app/api/chat_rooms/route.ts
  src/app/api/image/upload/route.ts
  src/provider/Providers.tsx
  src/stores/queries/useChatMessagesQuery.ts
  src/stores/queries/useChatRoomsQuery.ts
  src/stores/queries/useQuizQuery.ts
  src/stores/queries/useSubmitAnswerMutation.ts
  src/types/answer.type.ts
  src/types/chat.type.ts
  src/types/chatRoom.type.ts
  src/types/quiz.type.ts
  src/types/supabase.ts
Labels: feature

#64 fix: 유저 상태 오류 해결
  src/app/(auth)/login/_components/LoginContainer.tsx
  src/app/(main)/_components/HeaderContainer.tsx
  src/app/(main)/boards/_components/Comments/CommentForm.tsx
  src/app/(main)/boards/_components/Comments/CommentItem.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/_components/ActionNav.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowEditor.tsx
  src/app/(main)/boards/votes/_components/VoteWriteForm.tsx
  src/provider/Providers.tsx
  src/provider/contexts/userContext.tsx
Labels: bug

#65 feat/create-vote 짠 소비 등록시 유효성 검사
  src/app/(main)/boards/votes/_components/VoteWriteForm.tsx
Labels: feature

#75 feat/update-vote 짠 소비 수정
  src/apis/votes.ts
  src/app/(main)/boards/votes/[voteId]/_components/ActionNav.tsx
  src/app/(main)/boards/votes/[voteId]/page.tsx
  src/app/(main)/boards/votes/_components/VoteWriteForm.tsx
  src/app/(main)/boards/votes/edit/[voteId]/page.tsx
  src/app/api/votes/[voteId]/route.ts
  src/stores/queries/useVoteMutation.ts
Labels: feature

#74 feat: knowhow 관련 게시글, 댓글 CUD 에러처리
  src/apis/knowhow.ts
  src/app/api/knowhow/[knowhowId]/comments/route.ts
  src/app/api/knowhow/[knowhowId]/route.ts
  src/app/api/knowhow/comments/[commentId]/route.ts
  src/app/api/knowhow/route.ts
  src/hooks/useAlertModal.ts
  src/stores/queries/useKnowhowCommentMutation.ts
  src/stores/queries/useKnowhowMutation.ts
Labels: feature

#78 feat/delete-vote 찐 소비 삭제 및 에러 메시지 표시
  src/apis/votes.ts
  src/app/(main)/boards/votes/[voteId]/_components/ActionNav.tsx
  src/app/(main)/boards/votes/_components/VoteWriteForm.tsx
  src/app/api/knowhow/image/route.ts
  src/app/api/votes/[voteId]/route.ts
  src/stores/queries/useVoteMutation.ts
Labels: feature

#81 feat: 짠 노하우 좋아요 기능
  src/apis/knowhow.ts
  src/app/(main)/_components/HeaderContainer.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/_components/KnowhowLikes.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowItem.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowList.tsx
  src/app/api/knowhow/[knowhowId]/like/route.ts
  src/provider/Providers.tsx
  src/stores/queries/useKnowhowLikeMutation.ts
  src/stores/queries/useKnowhowLikesCountQuery.ts
  src/stores/queries/useKnowhowMutation.ts
  src/types/knowhow.type.ts
Labels: feature

#82 feat: 짠 노하우 댓글 유효성검사 / 짠 노하우 게시글 작성,수정시 취소기능 / 포인트 추가
  src/app/(main)/boards/_components/Comments/CommentForm.tsx
  src/app/(main)/boards/_components/Comments/CommentItem.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/_components/KnowhowLikes.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowEditor.tsx
  src/app/api/knowhow/route.ts
Labels: feature

#85 feat: 짠 노하우 게시글 작성 및 수정 유효성검사
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowEditor.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowPagination.tsx
  src/app/(main)/boards/knowhow/_constants/index.ts
  src/app/(main)/boards/votes/_components/VotesContainer.tsx
  src/stores/queries/useKnowhowMutation.ts
  src/stores/queries/useVoteMutation.ts
  src/utils/revalidation.ts
  src/utils/supabase/middleware.ts
Labels: feature

#86 feat: login 로직에 setSession 추가
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/api/auth/login/route.ts
  src/stores/zustand/quizStore.ts
Labels: feature

#88 Feature/mypage: 헤더부분, 마이페이지 UI
  package-lock.json
  package.json
  src/apis/auth/mypage/mypageInfo.ts
  src/app/(auth)/login/_components/LoginContainer.tsx
  src/app/(auth)/signUp/_components/SignUpContainer.tsx
  src/app/(main)/_components/HeaderContainer.tsx
  src/app/(main)/_components/HeaderMiddle.tsx
  src/app/(main)/_components/HeaderRightNone.tsx
  src/app/(main)/_components/HeaderRightUser.tsx
  src/app/(main)/mypage/_components/Info/InfoContainer.tsx
  src/app/(main)/mypage/_components/Info/InfoLeft.tsx
  src/app/(main)/mypage/_components/Info/InfoRight.tsx
  src/app/(main)/mypage/_components/Level/LevelContainer.tsx
  src/app/(main)/mypage/_components/Level/LevelDetails.tsx
  src/app/(main)/mypage/_components/Level/LevelTitle.tsx
  src/app/(main)/mypage/_components/MyPosts/MyPostsContainer.tsx
  src/app/(main)/mypage/_components/MypageContainer.tsx
  src/app/(main)/mypage/_components/OtherPosts/OtherPostsContainer.tsx
  src/app/(main)/mypage/_components/Point/PointContainer.tsx
  src/app/(main)/mypage/_components/Point/PointDetails.tsx
  src/app/(main)/mypage/_components/Point/PointGiftButton.tsx
  src/app/(main)/mypage/page.tsx
  src/app/(main)/mypage/setting/_components/Password/UserSettingPWContainer.tsx
  src/app/(main)/mypage/setting/_components/Password/checkPasswordValidity.tsx
  src/app/(main)/mypage/setting/_components/UserSettingContainer.tsx
  src/app/(main)/mypage/setting/_components/UserSettingContainer22.tsx
  src/app/(main)/mypage/setting/_components/UserSettingNickname.tsx
  src/app/(main)/mypage/setting/_components/UserSettingPassword copy.tsx
  src/app/(main)/mypage/setting/_components/UserSettingPassword.tsx
  src/app/(main)/mypage/setting/_components/validate.ts
  src/app/(main)/mypage/setting/page.tsx
  src/app/api/auth/callback/route.ts
  src/app/api/auth/getUser/route.ts
  src/app/api/auth/kakao/login/route.ts
  src/app/api/auth/kakao/logout/route.ts
  src/app/api/auth/logout/route.ts
  src/app/api/auth/mypage/info/route.ts
  src/app/api/auth/singout/route.ts
  src/app/globals.css
  src/provider/SupabaseProvider.tsx
  src/provider/contexts/userContext.tsx
Labels: feature

#98 feat/vote-buttons 짠 소비 GOOD / BAD 버튼 렌더링
  src/apis/votes.ts
  src/app/(main)/boards/votes/[voteId]/_components/ActionNav.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteButtons.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteContent.tsx
  src/app/api/votes/[voteId]/like/route.ts
  src/provider/Providers.tsx
  src/stores/queries/useVoteLikesQuery.ts
  src/types/vote.type.ts
  src/utils/supabase/middleware.ts
Labels: feature

#104 fix, rename, remove/mypage: api 테스트 중 merge conflict 문제 해결
  src/apis/auth/mypage/mypageInfo.ts
  src/app/(main)/mypage/_components/Info/InfoContainer.tsx
  src/app/(main)/mypage/_components/Info/InfoLeft.tsx
  src/app/(main)/mypage/_components/Info/InfoRight.tsx
  src/app/(main)/mypage/_components/Level/LevelContainer.tsx
  src/app/(main)/mypage/_components/Level/LevelDetails.tsx
  src/app/(main)/mypage/_components/Level/LevelTitle.tsx
  src/app/(main)/mypage/_components/MypageContainer.tsx
  src/app/(main)/mypage/_components/Point/PointContainer.tsx
  src/app/(main)/mypage/_components/Point/PointDetails.tsx
  src/app/(main)/mypage/_components/Point/PointGiftButton.tsx
  src/app/(main)/mypage/edit/_components/UserEditContainer.tsx
  src/app/(main)/mypage/edit/_components/UserEditNickname.tsx
  src/app/(main)/mypage/edit/_components/UserEditPassword.tsx
  src/app/(main)/mypage/edit/_components/checkPasswordValidity.tsx
  src/app/(main)/mypage/edit/page.tsx
  src/app/(main)/mypage/setting/_components/Password/UserSettingPWContainer.tsx
  src/app/(main)/mypage/setting/_components/UserSettingContainer.tsx
  src/app/(main)/mypage/setting/_components/UserSettingContainer22.tsx
  src/app/(main)/mypage/setting/_components/UserSettingPassword copy.tsx
  src/app/(main)/mypage/setting/_components/UserSettingPassword.tsx
  src/app/(main)/mypage/setting/_components/validate.ts
  src/app/(main)/mypage/setting/page.tsx
  src/app/api/auth/getUser/route.ts
  src/app/api/auth/mypage/info/route.ts
  src/app/api/auth/mypage/test/route.ts
  src/assets/logo.png
  src/assets/myprofileLogo.png
Labels: bug

#105 feat: users 테이블에 badge_url 추가 및 route handler 수정
  src/app/(main)/boards/knowhow/[knowhowId]/_components/PostContent.tsx
  src/app/(main)/boards/knowhow/_components/knowhowItem/KnowhowItem.tsx
  src/app/api/knowhow/[knowhowId]/route.ts
  src/app/api/knowhow/route.ts
  src/app/api/knowhow/top/route.ts
  src/types/knowhow.type.ts
  src/types/supabase.ts
Labels: feature

#106 feat: 포인트 랭킹 순위
  src/apis/ranking.ts
  src/app/(main)/_components/PointRankingContainer.tsx
  src/app/(main)/_components/PointRankingItem.tsx
  src/app/(main)/_components/PointRankingList.tsx
  src/app/(main)/page.tsx
  src/app/api/ranking/route.ts
  src/stores/queries/usePointRankingsQuery.ts
Labels: feature

#107 feat: Button 컴포넌트 bgColor prop 추가
  src/app/(main)/boards/knowhow/_components/KnowhowList.tsx
  src/components/Button/Button.tsx
Labels: feature

#109 feat/vote-comments 짠 소비 상세 페이지 좌우 버튼 구현
  src/apis/votes.ts
  src/app/(main)/boards/votes/[voteId]/_components/NavButton.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteContent.tsx
  src/app/(main)/boards/votes/_components/VoteItem.tsx
  src/app/(main)/boards/votes/_components/VotesContainer.tsx
  src/app/(main)/boards/votes/_components/VotesList.tsx
  src/app/api/votes/[voteId]/route.ts
  src/app/api/votes/posts/route.ts
  src/types/supabase.ts
  src/types/vote.type.ts
Labels: feature

#111 Feature/mypage: 중복확인 기능
  public/icons/mypage/circular_question.png
  public/icons/mypage/diamond.png
  public/icons/mypage/pencil.png
  src/apis/auth/mypage/mypageInfo.ts
  src/app/(main)/mypage/_components/Level/LevelContainer.tsx
  src/app/(main)/mypage/_components/Point/PointContainer.tsx
  src/app/(main)/mypage/edit/_components/UserEditNickname.tsx
  src/app/(main)/mypage/edit/_components/UserEditPassword.tsx
  src/app/(main)/mypage/edit/_components/checkValidity.tsx
  src/app/api/auth/mypage/test/route.ts
Labels: bug, feature

#117 Feature: 퀴즈 부분 애니메이션 추가 및 채팅방 UI 작업
  package-lock.json
  package.json
  public/icons/picture.png
  public/icons/quiz/animations_confetti.gif
  public/icons/quiz/animations_state_x.png
  public/icons/submit.png
  src/app/(auth)/signUp/_components/SignUpContainer.tsx
  src/app/(main)/chat/_components/ChatMessageContainer.tsx
  src/app/(main)/chat/_components/ChatMessageInput.tsx
  src/app/(main)/chat/_components/ChatMessageItem.tsx
  src/app/(main)/chat/_components/ChatMessageList.tsx
  src/app/(main)/quiz/_components/QuizAnswer.tsx
  src/app/globals.css
  tailwind.config.ts
Labels: feature

#120 feat: 내가 쓴 글, 좋아요 한 글 조회
  .prettierrc
  src/apis/knowhow.ts
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowFilter.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowList.tsx
  src/app/(main)/boards/knowhow/_components/Pagination.tsx
  src/app/(main)/boards/knowhow/_components/SortOptions.tsx
  src/app/(main)/boards/knowhow/_constants/index.ts
  src/app/(main)/boards/knowhow/page.tsx
  src/app/(main)/boards/votes/_components/VoteItem.tsx
  src/app/(main)/boards/votes/_components/VotesList.tsx
  src/app/(main)/mypage/_components/Info/InfoContainer.tsx
  src/app/(main)/mypage/_components/MyPosts/MyPostsContainer.tsx
  src/app/(main)/mypage/_components/OtherPosts/OtherPostsContainer.tsx
  src/app/(main)/mypage/like/_components/LikedKnowhowContainer.tsx
  src/app/(main)/mypage/like/page.tsx
  src/app/(main)/mypage/posts/_components/FilterOption.tsx
  src/app/(main)/mypage/posts/_components/MyKnowhowContainer.tsx
  src/app/(main)/mypage/posts/_components/MyPostsContainer.tsx
  src/app/(main)/mypage/posts/_components/MyVotesContainer.tsx
  src/app/(main)/mypage/posts/page.tsx
  src/app/api/knowhow/my/[userId]/route.ts
  src/app/api/knowhow/my/like/[userId]/route.ts
  src/app/api/votes/posts/my/[userId]/route.ts
  src/components/Modal/Modal.tsx
  src/provider/contexts/UserContext.tsx
  src/stores/queries/useLikedKnowhowsQuery.ts
  src/stores/queries/useMyKnowhowsQuery.ts
  src/stores/queries/useMyVotesQuery.ts
  src/types/supabase.ts
  src/types/vote.type.ts
Labels: feature

#121 feat/vote-comments 짠 소비 상세 페이지 댓글 구현
  src/apis/votes.ts
  src/app/(main)/boards/_components/Comments/CommentActions.tsx
  src/app/(main)/boards/_components/Comments/CommentEditForm.tsx
  src/app/(main)/boards/_components/Comments/CommentForm.tsx
  src/app/(main)/boards/_components/Comments/CommentItem.tsx
  src/app/(main)/boards/_components/Comments/CommentsContainer.tsx
  src/app/(main)/boards/_components/Comments/CommentsList.tsx
  src/app/(main)/boards/knowhow/[knowhowId]/page.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/boards/votes/[voteId]/page.tsx
  src/app/(main)/boards/votes/_components/VotesContainer.tsx
  src/app/api/votes/[voteId]/comments/route.ts
  src/app/api/votes/comments/[commentId]/route.ts
  src/stores/queries/useKnowhowCommentMutation.ts
  src/stores/queries/useVoteCommentMutation.ts
  src/stores/queries/useVoteCommentsQuery.ts
  src/types/vote.type.ts
Labels: bug, feature

#124 Feature/mypage : 로그아웃 기능
  src/apis/auth/auth.ts
  src/apis/auth/mypage/mypageInfo.ts
  src/app/(auth)/authValidity.tsx
  src/app/(auth)/login/_components/LoginEmailForm.tsx
  src/app/(auth)/login/_components/TestLogin.tsx
  src/app/(auth)/login/page.tsx
  src/app/(main)/_components/HeaderContainer.tsx
  src/app/(main)/_components/HeaderRightNone.tsx
  src/app/(main)/_components/HeaderRightUser.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/mypage/_components/Level/LevelContainer.tsx
  src/app/(main)/mypage/_components/Point/PointContainer.tsx
  src/app/(main)/mypage/edit/_components/TestPassword.tsx
  src/app/(main)/mypage/edit/_components/TestUpdatePassword.tsx
  src/app/(main)/mypage/edit/_components/UserEditContainer.tsx
  src/app/api/auth/login/route.ts
  src/app/api/auth/mypage/password/route.ts
  src/app/globals.css
  src/app/layout.tsx
Labels: feature

#126 feat: 짠 소비평가 투표기능
  src/apis/votes.ts
  src/app/(main)/boards/votes/[voteId]/_components/VoteButtons.tsx
  src/app/(main)/boards/votes/[voteId]/page.tsx
  src/app/(main)/mypage/posts/_components/MyVotesContainer.tsx
  src/app/api/knowhow/my/[userId]/route.ts
  src/app/api/votes/[voteId]/like/route.ts
  src/app/api/votes/posts/route.ts
  src/stores/queries/useVoteLikeMutation.ts
  src/types/vote.type.ts
Labels: feature

#129 feat/vote-nav-button 짠 소비 네비게이션 버튼 구현
  src/app/(main)/boards/votes/[voteId]/_components/NavButton.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteContent.tsx
  src/app/api/votes/[voteId]/route.ts
Labels: feature

#133 feat: 메인 화면 레이아웃 수정 및 회원가입 폼 리팩토링 및 유효성 검사 추가
  public/home/home_live_banner.png
  public/icons/trophy.png
  src/apis/signup.ts
  src/app/(auth)/signUp/_components/EmailForm.tsx
  src/app/(auth)/signUp/_components/NicknameForm.tsx
  src/app/(auth)/signUp/_components/PasswordForm.tsx
  src/app/(auth)/signUp/_components/RecheckPasswordForm.tsx
  src/app/(auth)/signUp/_components/SignUpContainer.tsx
  src/app/(main)/_components/LeftSection/LeftSection.tsx
  src/app/(main)/_components/LeftSection/LiveChattingBanner.tsx
  src/app/(main)/_components/LeftSection/TopVotes.tsx
  src/app/(main)/_components/RightSection/PointRankingContainer.tsx
  src/app/(main)/_components/TopSection/TopSection.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/page.tsx
  src/app/globals.css
  src/provider/contexts/UserContext.tsx
  src/types/user.type.ts
Labels: feature

#134 feat: 투표시 포인트 적립 / Button컴포넌트 bgColor prop type 추가
  src/app/(main)/boards/votes/[voteId]/_components/VoteButtons.tsx
  src/app/(main)/boards/votes/[voteId]/_components/VoteContent.tsx
  src/app/(main)/boards/votes/_components/VoteWriteForm.tsx
  src/app/api/votes/[voteId]/like/route.ts
  src/components/Button/Button.tsx
Labels: feature

#135 feat: 댓글 유저 배지 추가
  src/app/(main)/boards/_components/Comments/CommentItem.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowContainer.tsx
  src/app/(main)/boards/knowhow/_components/KnowhowEditor.tsx
  src/app/(main)/boards/knowhow/_components/knowhowItem/KnowhowItem.tsx
  src/app/api/knowhow/[knowhowId]/comments/route.ts
  src/app/api/knowhow/comments/[commentId]/route.ts
  src/app/api/knowhow/my/like/[userId]/route.ts
  src/app/api/votes/[voteId]/comments/route.ts
  src/app/api/votes/posts/my/[userId]/route.ts
  src/app/api/votes/posts/top/route.ts
  src/app/globals.css
  src/types/knowhow.type.ts
  src/types/vote.type.ts
Labels: feature

#141 feat/create-vote-page-ui 짠 소비 작성 페이지 UI 구현 및 버그 수정
  src/app/(main)/boards/votes/[voteId]/_components/VoteContent.tsx
  src/app/(main)/boards/votes/_components/VoteItem.tsx
  src/app/(main)/boards/votes/_components/VoteWriteForm.tsx
Labels: bug, feature

#139 feat: 닉네임 변경 기능 완성(중복확인 통과 후 update 로직)
  src/apis/auth.ts
  src/app/(auth)/authValidity.tsx
  src/app/(main)/mypage/_components/InfoContainer.tsx
  src/app/(main)/mypage/_components/MypageContainer.tsx
  src/app/(main)/mypage/edit/_components/UserEditNickname.tsx
  src/app/api/auth/mypage/nickname/route.ts
Labels: feature

#143 feat/my-point-detail-page 사용자 포인트 내역 가져오기
  src/apis/point.ts
  src/app/(main)/boards/votes/[voteId]/page.tsx
  src/app/(main)/mypage/_components/PointContainer.tsx
  src/app/(main)/mypage/_components/Points/MyCurrentPoints.tsx
  src/app/(main)/mypage/_components/Points/MyPointsHistoryTable.tsx
  src/app/(main)/mypage/point/page.tsx
  src/app/api/points/[userId]/route.ts
  src/stores/queries/usePointsQuery.ts
  src/types/point.type.ts
Labels: feature
